name: Build & Deploy to K3s

on:
  push:
    branches: [ "main" ]

jobs:
  login:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout code
          uses: actions/checkout@v3
      
        - name: Log in to Docker Hub
          uses: mr-smithers-excellent/docker-build-push@v6
          with:
            image: docker-hub-repo/image-name
            registry: docker.io
            username: ${{ vars.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Build and push Docker image
        run: |
          docker build -t yourdockerhub/auth-service:latest ./services/auth
          docker push yourdockerhub/auth-service:latest

      - name: Setup kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBECONFIG }}" > ~/.kube/config

      - name: Deploy to K3s
        run: kubectl apply -f k8s/
